import { CircleDollarSign, Gem, Landmark, Plus, UploadCloud } from "lucide-react";
import type { ChangeEvent } from "react";
import { defaultPurity } from "../../product-purity";
import type { ProductFieldErrors } from "../../product-validation";
import type { ProductDraft, ProductImage } from "../product-form.types";
const metals=[{value:"GOLD",label:"طلا"},{value:"SILVER",label:"نقره"},{value:"COPPER",label:"مس"},{value:"PLATINUM",label:"پلاتین"}] as const;
export function StepBasicInfo({draft,patch,errors={}}:{draft:ProductDraft;patch:(value:Partial<ProductDraft>)=>void;errors?:ProductFieldErrors}){
 const chooseMetal=(metal:ProductDraft["metal"])=>patch({metal,carat:defaultPurity(metal),...(metal!=="GOLD"&&draft.category==="COIN"?{category:"JEWELRY"}:{})});
 const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const selected=Array.from(event.target.files??[]);const files=selected.filter(file=>file.size<=1024*1024);if(files.length!==selected.length)window.alert("حجم هر تصویر باید حداکثر ۱ مگابایت باشد.");const start=draft.images.length;const images=await Promise.all(files.map((file,index)=>new Promise<ProductImage>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),name:file.name,preview:String(reader.result),isPrimary:start===0&&index===0});reader.readAsDataURL(file)})));patch({images:[...draft.images,...images]});event.target.value=""};
 return <><section className="form-section"><h3>اطلاعات اصلی محصول</h3><div className="basic-columns"><div><label>عنوان محصول *<input className={errors.title?"field-invalid":""} value={draft.title} onChange={e=>patch({title:e.target.value})}/>{errors.title&&<small className="field-error">{errors.title}</small>}</label><label>کد محصول (SKU)<input value={draft.sku} onChange={e=>patch({sku:e.target.value})}/></label></div><div><div className="metal-picker"><span>نوع فلز *</span><div>{metals.map(item=><button type="button" key={item.value} className={draft.metal===item.value?"selected":""} onClick={()=>chooseMetal(item.value)}>{item.label}</button>)}</div></div><div className="category-field"><span>دسته محصول *</span><div><button type="button" className={draft.category==="JEWELRY"?"selected":""} onClick={()=>patch({category:"JEWELRY"})}><Gem/>{draft.metal==="SILVER"?"جواهر نقره":"جواهرات"}</button>{draft.metal==="GOLD"&&<button type="button" className={draft.category==="COIN"?"selected":""} onClick={()=>patch({category:"COIN"})}><Landmark/>سکه</button>}<button type="button" className={draft.category==="BULLION"?"selected":""} onClick={()=>patch({category:"BULLION"})}><CircleDollarSign/>{draft.metal==="SILVER"?"شمش نقره":"شمش"}</button></div></div><label>جنسیت<select value={draft.gender} onChange={e=>patch({gender:e.target.value as ProductDraft["gender"]})}><option value="WOMAN">زنانه</option><option value="MAN">مردانه</option><option value="UNISEX">مشترک</option><option value="KID">کودک</option><option value="NONE">بدون جنسیت</option></select></label></div><label className="description-column">توضیحات محصول<textarea value={draft.description} onChange={e=>patch({description:e.target.value})} maxLength={500}/><small>{draft.description.length}/۵۰۰</small></label></div></section><section className="form-section"><h3>تصاویر محصول</h3><div className="image-manager"><label className="image-drop"><UploadCloud/><strong>برای بارگذاری تصاویر کلیک کنید</strong><small>JPG، PNG یا WEBP — حداکثر ۵ مگابایت</small><input type="file" accept="image/*" multiple onChange={upload}/></label><div className="image-list">{draft.images.map(image=><button type="button" key={image.id} className={image.isPrimary?"primary":""} onClick={()=>patch({images:draft.images.map(item=>({...item,isPrimary:item.id===image.id}))})}><img src={image.preview} alt=""/>{image.isPrimary&&<span>اصلی</span>}</button>)}<label className="add-image"><Plus/>افزودن تصویر<input type="file" accept="image/*" multiple onChange={upload}/></label></div></div></section></>;
}
